# -*- coding: utf-8 -*-
"""Web Scraping of Weather Data.ipynb

Automatically generated by Colab.

"""

# Import libraries
!pip install requests beautifulsoup4

!pip install requests

import requests
from bs4 import BeautifulSoup
import sqlite3

# 1) Identify the webpage from which to extract the data.

# Weather page URL (change based on your location)
url = "https://weather.com/es-CO/tiempo/hoy/l/399c3cf061cb7211a2bdf7b0ec12df5559a54d0896edb337425ecb26b5cd3b48"

# 2) Use Requests and BeautifulSoup to fetch and parse the HTML.

# Make the request
response = requests.get(url)

if response.status_code == 200:
    print("Request successfully!")
    html = response.text
else:
    print(f"Wrong with the request: {response.status_code}")

#Parsear the  HTML
soup = BeautifulSoup(html, "html.parser")

# 3) Extract relevant information such as temperature, humidity, and weather

# Find html tags with soup.find
today_detals = soup.find_all('div', class_ = 'ListItem--listItem--UuEqg WeatherDetailsListItem--WeatherDetailsListItem--HLP3I')
print('Detail:', type(today_detals))
print('d:', len(today_detals))

# Find html tags with soup.find
city_hour = soup.find_all('div', class_ = 'CurrentConditions--header--z8kOV')
print('Detalles:', type(city_hour))
print('Longitud:', len(city_hour))

#Print the City
city = city_hour[0].h1.text
city_=city.split()
print(city_)

#Print register Time
hour = city_hour[0].span.text
hour_=hour[15:21].split()
print(hour_)

#Save the meteorological indicators in a list to be stored in an SQL database.
F=[]
for i in range(len(today_detals)):
  date = today_detals[i]
  if date.span:
    a=date.span.text
  else:
    a=date.div.text
  F.append(a)
city_.extend(hour_)
city_.extend(F)

print(city_)

# 4) Store the extracted data in an SQLite database.

# Connect or create the SQLite database
conn = sqlite3.connect('weather.db')
cursor = conn.cursor()

# Create a table (if it doesn't exist)
cursor.execute('''
CREATE TABLE IF NOT EXISTS weather (
    id INTEGER PRIMARY KEY,
    data TEXT
)
''')

# Insert the list items into the database
for data in city_:
    cursor.execute('INSERT INTO weather (data) VALUES (?)', (data,))

# Save (commit) the changes
conn.commit()

# Close the connection
conn.close()

# Connect to the 'weather.db' database
conn = sqlite3.connect('weather.db')
# Create a cursor to execute SQL commands.
cursor = conn.cursor()

# SQL query that selects all records from the table named weather
cursor.execute('SELECT * FROM weather')
# This command retrieves all the results of the executed query.
rows = cursor.fetchall()


for row in rows:
    print(row)

# Close the connection
conn.close()